### ISSUE TITLE
Can I train the model on KITTI dataset?

### ISSUE THREAD

**Issue by sunnyHelen** [zju3dv/RVL-Dynamic#2]
Do you ever try to train or test on KITTI dataset? Can I use your model to predict trajectory on other dataset except 7 Scenes and RobotCar?

**Comment by drinkingcoder** [comment]
I didn't try it on KITTI dataset.
The model is trained for a specific scene. 
You need to compute the prior distribution and train a new model if you want to test on KITTI dataset.
